SELECT A.PRODUCT_CODE AS 'PRODUCT_CODE',  A.PRICE * SUM(B.SALES_AMOUNT) AS 'SALES'
FROM PRODUCT A LEFT JOIN OFFLINE_SALE B
    ON A.PRODUCT_ID = B.PRODUCT_ID
WHERE B.PRODUCT_ID
GROUP BY A.PRODUCT_CODE
ORDER BY 2 DESC, 1 ASC;
